lexer grammar MilvusLexer;

LIKE: 'LIKE';
EXISTS: 'EXISTS';
TEXTMATCH: 'TEXT_MATCH';
PHRASEMATCH: 'PHRASE_MATCH';
RANDOMSAMPLE: 'RANDOM_SAMPLE';
INTERVAL: 'INTERVAL';
ISO: 'ISO';
MINIMUM_SHOULD_MATCH: 'MINIMUM_SHOULD_MATCH';
IS: 'IS';
NULL: 'NULL';
NOT: '!' | 'NOT';
IN: 'IN';
TRUE: 'TRUE';
FALSE: 'FALSE';

DOLLAR: '$';
ASSIGN: '=';
EQ: '==';
NE: '!=';
LT: '<';
LE: '<=';
GT: '>';
GE: '>=';

ADD: '+';
SUB: '-';
MUL: '*';
DIV: '/';
MOD: '%';
POW: '**';
SHL: '<<';
SHR: '>>';
BAND: '&';
BOR: '|';
BXOR: '^';
BNOT: '~';
BACKSLASH: '\\';

AND: '&&' | 'AND';
OR: '||' | 'OR';

OPEN_SQUARE_BRACKET: '[';
CLOSE_SQUARE_BRACKET: ']';
OPEN_PARENTHESIS: '(';
CLOSE_PARENTHESIS: ')';
OPEN_BRACE: '{';
CLOSE_BRACE: '}';

IDENTIFIER: (LETTER | '_') (LETTER | DIGIT | '_')*;

INTEGER_VALUE: DIGIT+;

DECIMAL_VALUE:
	INTEGER_VALUE '.' INTEGER_VALUE?
	| '.' INTEGER_VALUE
	| INTEGER_VALUE ('.' DIGIT*)? EXPONENT
	| '.' INTEGER_VALUE EXPONENT;

OCTAL_VALUE: '0' OCTAL_DIGIT+;

HEXADECIMAL_VALUE: '0' 'X' HEXADECIMAL_DIGIT+;

BINARY_VALUE: '0' 'B' BINARY_DIGIT+;

SINGLE_QUOTED_STRING: '\'' (~'\'')* '\'';

DOUBLE_QUOTED_STRING: '"' (~'"')* '"';

fragment DIGIT: [0-9];
fragment OCTAL_DIGIT: [0-7];
fragment HEXADECIMAL_DIGIT: [0-9a-fA-F];
fragment BINARY_DIGIT: [0-1];
fragment LETTER: [a-zA-Z];
fragment EXPONENT: 'E' [+-]? DIGIT+;

WS: [ \t\r\n\f]+ -> channel(HIDDEN);
