# Copyright (C) 2019-2020 Zilliz. All rights reserved.#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under the License.

defaultPartitionName: "_default" # old: common.xxxx
defaultIndexName: "_default_idx"

etcd:
  endpoints:
    - localhost:2379
  rootPath: by-dev
  metaSubPath: meta # metaRootPath = rootPath + '/' + metaSubPath
  kvSubPath: kv # kvRootPath = rootPath + '/' + kvSubPath
  segmentBinlogSubPath: datacoord/binlog/segment  # Full Path = rootPath/metaSubPath/segmentBinlogSubPath
  collectionBinlogSubPath: datacoord/binlog/collection # Full Path = rootPath/metaSubPath/collectionBinglogSubPath
  flushStreamPosSubPath: datacoord/flushstream # Full path = rootPath/metaSubPath/flushStreamPosSubPath
  statsStreamPosSubPath: datacoord/statsstream # Full path = rootPath/metaSubPath/statsStreamPosSubPath

minio:
  address: localhost
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  bucketName: "a-bucket"

pulsar:
  address: localhost
  port: 6650
  maxMessageSize: 5242880 # 5 * 1024 * 1024 Bytes

rocksmq:
  path: /var/lib/milvus/rdb_data

rootCoord:
  address: localhost
  port: 53100
  maxPartitionNum: 4096 # old: rootcooord.xxx
  minSegmentSizeToEnableIndex: 1024
  timeout: 3600 # time out, 5 seconds
  timeTickInterval: 200 # ms

proxy:
  port: 19530
  timeTickInterval: 200 # ms
  msgStream:
    insertBufSize: 1024 # old:
    searchBufSize: 512
    searchResultRecvBufSize: 1024
    searchResultPulsarBufSize: 1024
    timeTickBufSize: 512
  maxNameLength: 255
  maxFieldNum: 64
  maxDimension: 32768

  #msgStream:
    #insert:
      #bufSize: 1024 # msgPack chan buffer size
    #search:
      #bufSize: 512
    #searchResult:
      #recvBufSize: 1024 # msgPack chan buffer size
      #pulsarBufSize: 1024 # pulsar chan buffer size
    #timeTick:
      #bufSize: 512
  #maxNameLength: 255
  #maxFieldNum: 64
  #maxDimension: 32768

queryCoord:
  address: localhost
  port: 19531

queryNode:
  gracefulTime: 1000 # ms, for search
  port: 21123
  statsPublishInterval: 1000 # milliseconds
  flowGraph:
    maxQueueLength: 1024
    maxParallelism: 1024
  msgStream:
    searchRecvBufSize: 512
    searchPulsarBufSize: 512
    searchResultRecvBufSize: 64

  #stats:
    #publishInterval: 1000 # milliseconds
  #dataSync:
    #flowGraph:
      #maxQueueLength: 1024
      #maxParallelism: 1024
  #msgStream:
    #search:
      #recvBufSize: 512
      #pulsarBufSize: 512
    #searchResult:
      #recvBufSize: 64

indexCoord:
  address: localhost
  port: 31000

indexNode:
  port: 21121

dataCoord:
  address: localhost
  port: 13333
  segment: # old: datacoord.xxx
    maxSize: 512 # MB
    sealProportion: 0.75
    assignmentExpiration: 2000 # ms

dataNode:
  port: 21124
  flowGraph: #old
    maxQueueLength: 1024
    maxParallelism: 1024
  flushBufSize: 32000

  #dataSync:
    #flowGraph:
      #maxQueueLength: 1024
      #maxParallelism: 1024
  #flush:
    ## max buffer size to flush
    #insertBufSize: 32000 # number of rows

log:
  level: debug # info, warn, error, panic, fatal
  file:
    rootPath: "" # default to stdout, stderr
    maxSize: 300 # MB
    maxAge: 10 # day
    maxBackups: 20
  format: text # text/json

msgChannel:
  # channel name generation rule: ${namePrefix}-${ChannelIdx}
  #chanNamePrefix:
    rootCoordTimeTick: "rootcoord-timetick"
    rootCoordStatistics: "rootcoord-statistics"
    search: "search"
    searchResult: "searchResult"
    proxyTimeTick: "proxyTimeTick"
    queryTimeTick: "queryTimeTick"
    queryNodeStats: "query-node-stats"
    # cmd for loadIndex, flush, etc...
    cmd: "cmd"
    dataCoordInsertChannel: "insert-channel-"
    dataCoordStatistic: "datacoord-statistics-channel"
    dataCoordTimeTick: "datacoord-timetick-channel"
    dataCoordSegmentInfo: "segment-info-channel"

  # sub name generation rule: ${subNamePrefix}-${NodeID}
  #subNamePrefix: #old
    rootCoordSubNamePrefix: "rootcoord"
    proxySubNamePrefix: "proxy"
    queryNodeSubNamePrefix: "queryNode"
    dataNodeSubNamePrefix: "dataNode"
    dataCoordSubNamePrefix: "dataCoord"

